name: Coderco CICD

on: [push] 

jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      -name: checkout code
      uses: actions/checkout@v2
      -name: we are testing this workflow
      run: echo Hello everyone!
